development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: apprentinces_api_dev
  pool: 5

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  host: localhost
  database: apprentinces_api_test
  pool: 5
